name: Release Rust Binaries

permissions:
  contents: write # Needed to create releases

on:
  push:
    tags:
      - "v[0-9]+.*" # Triggers on tags like v0.1.0

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # No changelog to avoid errors

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-pc-windows-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Install musl-tools for musl targets
        if: contains(matrix.target, 'musl')
        run: sudo apt-get update && sudo apt-get install -y musl-tools
      - name: Install mingw-w64 for Windows GNU target
        if: contains(matrix.target, 'windows-gnu')
        run: sudo apt-get update && sudo apt-get install -y mingw-w64
      - name: Build and Upload Binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: midetor # Your binaries
          target: ${{ matrix.target }}
          archive: gz # Compress as .tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
