name: Release midetor Binary

permissions:
  contents: write # Needed to create releases

on:
  push:
    tags:
      - "v[0-9]+.*" # Triggers on tags like v0.1.0

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # No changelog

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - x86_64-pc-windows-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Install musl-tools for musl targets
        if: contains(matrix.target, 'musl')
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
      - name: Install mingw-w64 for Windows GNU target
        if: contains(matrix.target, 'windows-gnu')
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64
      - name: Build binary
        run: |
          cargo build --release --target ${{ matrix.target }}
          ls -la target/${{ matrix.target }}/release/
      - name: Upload midetor
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: midetor
          target: ${{ matrix.target }}
          archive: midetor-${{ matrix.target }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
